language: python

python:
    - 2.7

install:
    - python setup.py install
    - pip install pytest

script:
    - python -c "import sflock ; exit(len(sflock.supported()) != 4)"
    - py.test

    - sudo apt-get -y install p7zip-full
    - python -c "import sflock ; exit(len(sflock.supported()) != 5)"
    - py.test

    - sudo apt-get -y install rar
    - python -c "import sflock ; exit(len(sflock.supported()) != 6)"
    - py.test

    - sudo apt-get -y install unace-nonfree
    - python -c "import sflock ; exit(len(sflock.supported()) != 7)"
    - py.test
