language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - os: osx
      language: generic

install:
    - python setup.py develop
    - pip install pytest pytest-cov coveralls
    - |
      if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        brew update || brew update
        brew install libmagic
      fi

script:
    - 'python -c "import sflock ; exit(len(sflock.supported()) != 8)"'
    - 'py.test --cov=sflock'

    - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo apt-get -y install p7zip-full'
    - '[[ $TRAVIS_OS_NAME == "linux" ]] && python -c "import sflock ; exit(len(sflock.supported()) != 9)"'
    - '[[ $TRAVIS_OS_NAME == "linux" ]] && py.test --cov=sflock --cov-append'

    - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo apt-get -y install rar'
    - '[[ $TRAVIS_OS_NAME == "linux" ]] && python -c "import sflock ; exit(len(sflock.supported()) != 10)"'
    - '[[ $TRAVIS_OS_NAME == "linux" ]] && py.test --cov=sflock --cov-append'

    - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo apt-get -y install unace-nonfree'
    - '[[ $TRAVIS_OS_NAME == "linux" ]] && python -c "import sflock ; exit(len(sflock.supported()) != 11)"'
    - '[[ $TRAVIS_OS_NAME == "linux" ]] && py.test --cov=sflock --cov-append'

after_success:
    - coveralls
