language: python

python:
    - 2.7

install:
    - sudo python setup.py install

script:
    - python -c "import sflock ; exit(len(sflock.supported()) == 4)"

    - sudo apt install p7zip-full
    - python -c "import sflock ; exit(len(sflock.supported()) == 5)"

    - sudo apt install unrar
    - python -c "import sflock ; exit(len(sflock.supported()) == 6)"

    - sudo apt install unace-nonfree
    - python -c "import sflock ; exit(len(sflock.supported()) == 7)"

    - py.test
